### ISSUE TITLE
Feature not marked as done when done with JOSM

### ISSUE THREAD

**Issue by tuxayo** [aaronlidman/osmly#45]
After uploading with JOSM I come back to the page and I click "Yes, uploaded" but nothing happens, I'm still on the same feature and in the list it's not marked as done.
Is that normal?

Tested on two parks on the current demo with firefox and chromium
Alta Loma Park, North Hollywood Park

**Comment by aaronlidman** [comment]
Huh, you're right. Not sure what happened there, I'll look into it.
