### ISSUE TITLE
Can OSMLY import from point to polygon

### ISSUE THREAD

**Issue by maning** [aaronlidman/osmly#56]
Awesone tool! We are planning a series of managed import of schools from a government db, the data is spreadsheet of schools where each school has a point location.  Our idea is use this as a reference to improve OSM data and add the attributes from schools database.

The planned process is the following:
1. Show users a list or a map of school locations.
2. Edit OSM by adding school grounds, buildings and other facilities within the school.
3. Copy tags from the schools db.
4. If the schools already exist in OSM, either, flag as compelte/mapped or add additional tags from the reference db.

I'm not sure whether osmly is the best tool (off-the-shelf) or another tool would suffice.  Note that we don't want a bot to just import a fix later. :)

**Comment by aaronlidman** [comment]
Hi Maning,
- It doesn't currently convert points to polygons, but I do see the value in doing that. I would like it to do something like that in the future.
- This would be fairly simple to add with the Leaflet draw plugin. The toolbar on the left side: http://leaflet.github.io/Leaflet.draw/
- I'd prefer not to add additional details like buildings etc... leaving that to more capable editors like iD.

I've thought about doing this before, just haven't gotten around to it. In the United States there was an import of many thousands of points for most parks and schools and I would like it to work with those. It would be simple to make it work with any list of points though.

I would like to add something like this, just not sure when I'll get around to it.

**Comment by maning** [comment]
Thanks @aaronlidman,  support for points would be great (created a separate issue for that).  Will send feedback as we move with the planned import.
