### ISSUE TITLE
server setup guidance?

### ISSUE THREAD

**Issue by mikelmaron** [aaronlidman/osmly#66]
Hi, I'm taking a look at putting osmly to work for an import, and need some guidance on server setup for testing. Note, I'm not experienced with node, so may be doubly ignorant.

So far, I've cloned the repo, and run 

% npm install
% make

I got some test data in a GeoJSON file, and built the sqlite database

% python server/build.py test-data.geojson

That all looks fine. Then I go to what I think is the next step, running the server

$ node server/server.js 

and get an Error. What am I mising?

**Comment by aaronlidman** [comment]
Excellent!

The server component has it's own dependencies, which I forgot to document. Just go into the server directory and run `npm install` again. This will install the server dependencies only in the server/ directory. I updated the documentation to reflect this: https://github.com/aaronlidman/osmly#local-development

One slightly confusing thing that might come up is that the sqlite database must be in the server directory and you must initialize server.js from within the server directory. Admittedly, this is all a bit of a mess and should be simplified.

**Comment by mikelmaron** [comment]
thanks that did it!
