### ISSUE TITLE
Handle point geometries

### ISSUE THREAD

**Issue by mikelmaron** [aaronlidman/osmly#67]
Looking into point geometries. Started off by adding a "geometry" argument to build.py. Could also simply work base of what it encounters in the GeoJSON file.

https://github.com/mapkibera/osmly/commit/e2d1ba1d21c69fc4d2421da4eb1c9da43600e0ef

Firing up the server and dev-template, getting a javascript error at 
https://github.com/aaronlidman/osmly/blob/gh-pages/js/osmly/osmly.map.js#L164

Appears that the layer created for a GeoJSON point doesn't have an "editing" property. Have looked if there's a different way to enable editing on a Point, but have not found anything yet. Don't know if this is an issue in GeoJSON parsing or leaflet-draw.

**Comment by aaronlidman** [comment]
@mikelmaron This looks great. Just a minor preference, I'd like another geometry mode, `all`, and that should be the default. I can make the change.

The point issue makes sense, points in leaflet aren't editable they are draggable. I can merge this in and work on the other issues for a couple hours tonight. Sound good?

**Comment by mikelmaron** [comment]
@aaronmlidman geometry=all sounds good

I just in fact spotted the draggable issue and committed
https://github.com/mapkibera/osmly/commit/672d77c33ccae9d246c031087dc088d19b3be23a

Now I can edit points, but getting a 400 Bad Request on upload to the API. "Cannot parse valid node from xml string ... Changeset id is missing". Further, it then jumps to another point to edit, and auto-submits.

Seems like it's close. If you have some time tonight tonight to nail down these final pieces, awesome, I'll take a rest.
