### ISSUE TITLE
oauth CORS problem when switching writeApi to openstreetmap.org

### ISSUE THREAD

**Issue by mikelmaron** [aaronlidman/osmly#73]
Investigating. Any ideas how this should work?

XMLHttpRequest cannot load https://www.openstreetmap.org/oauth/request_token. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1' is therefore not allowed access.

**Comment by aaronlidman** [comment]
but it works fine on api06.dev.openstreetmap.org ?

**Comment by mikelmaron** [comment]
yes, works fine on api06.dev.openstreetmap.org (for ex. http://api06.dev.openstreetmap.org/changeset/40964)

**Comment by mikelmaron** [comment]
ok, i registered an application as an oauth consumer, noted the key and secret in settings, and seems fine now.

**Comment by aaronlidman** [comment]
Oh yeah I should have included the old one I used for testing. :+1: Will jump on a few of these other issues later today.
